name: my_sport_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # QUẢN LÝ TRẠNG THÁI (State Management)
  provider: ^6.1.2

  # KẾT NỐI MẠNG & GỌI API (Network Layer)
  dio: ^5.4.2 # tự động gắn Token và dễ dàng upload ảnh form-data
  socket_io_client: ^3.0.0-beta.3 # Bắt buộc phải có để nghe ngóng tin nhắn Real-time

  # LƯU TRỮ CỤC BỘ (Local Storage)
  shared_preferences: ^2.2.2 # Lưu Token đăng nhập để lần sau mở app không phải login lại

  # TIỆN ÍCH DỮ LIỆU & ĐỊNH DẠNG (Utilities)
  intl: ^0.19.0 # Format ngày tháng (chuyển "2026-03-06T18:56:50" thành "18:56 - 06/03/2026")
  jwt_decoder: ^2.0.1 # Đọc dữ liệu giải mã từ Token

  # TÍNH NĂNG ĐẶC THÙ
  image_picker: ^1.0.7 # Mở thư viện/camera chọn ảnh Avatar, ảnh Đội bóng
  cached_network_image: ^3.3.1 # Tải và lưu cache ảnh Cloudinary cực mượt, không bị giật lag
  geolocator: ^11.0.0 # Lấy tọa độ GPS (Long/Lat) để gọi API "Tìm quanh đây"
  flutter_card_swiper: ^7.0.0 # Thư viện tạo UI quẹt thẻ LIKE/DISLIKE

  # UI & HIỆU ỨNG (Giao diện)
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Font chữ đẹp không cần tải file local
  flutter_svg: ^2.0.10 # Vẽ icon SVG sắc nét
  fluttertoast: ^8.2.4 # Hiện thông báo nổi (Toast) báo lỗi hoặc thành công

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
